---
- name: enable and start services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - mariadb
    - httpd24-httpd
- name: run maria secure installation
  script: /root/maria_secure_installation.sh
- name: add snort group
  group:
    name: snort
    system: True
- name: add snort user
  user:
    name: snort
    system: True
- name: run barnyard and snorby install
  script: /root/barn_snor.sh
- name: ensure dir exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /var/log/barnyard2
    - /var/log/snort
- name: set dir owner
  file:
    path: /var/log/barnyard2/
    owner: snort
    group: snort
    state: directory
- name: set file perms
  file:
    path: /etc/snort/.mariadb_snortpw
    mode: 0600
- name: Install selinux policy to allow NetWorkManager to start a snort service
  shell: /usr/sbin/semodule -i /usr/share/selinux/packages/foss-ids/foss_snort.pp
- name: enable services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - barnyard2
    - snorby
