---
- name: enable services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - mariadb
    - httpd24-httpd
- name: run maria secure installation
  script: /root/maria_secure_installation.sh
- name: run barnyard and snorby install
  script: /root/barn_snor.sh
- name: ensure dir exist
  file:
    path: /var/log/barnyard2
    state: directory
    mode: 0755
  with_items:
    - /var/log/barnyard2
    - /var/log/snort
- name: set dir owner
  file:
    path: /var/log/barnyard2/
    owner: snort
    group: snort
    state: directory
    #- name: set file owner
    #file:
    #    path: "{{ item }}"
    #    owner: snort
    #    group: snort
    #  with_items:
    #    - /etc/snort/.mariadb_snortpw
    #    - /var/log/snort/barnyward2.waldo
    #- name: ensure file exist
    #  file:
    #    path: /var/log/snort/barnyward2.waldo
    #    state: touch
    #    mode: 0755
- name: set file perms
  file:
    path: /etc/snort/.mariadb_snortpw
    mode: 0600
- name: Install selinux policy to allow NetWorkManager to start a snort service
  shell: /usr/sbin/semodule -i /usr/share/selinux/packages/foss-ids/foss_snort.pp
- name: enable services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - barnyard2
    - snorby
