---
# allow apache reading dumps
- name: set acl on dir
  acl:
    path: /home/tcpdump
    entity: apache
    etype: user
    permissions: rx
    state: present

- name: check if dumper_tcpdup.pp exist
  stat:
    path: /usr/share/selinux/packages/foss-traffic-capture/dumper_tcpdump.pp
  register: s
- name: Install traffic capture selinux policy package dumper_tcpdump
  command: /usr/sbin/semodule -i /usr/share/selinux/packages/foss-traffic-capture/dumper_tcpdump.pp
  notify: restorecon
  when: s.stat.exists

- name: check if dumper_httpd.pp exist
  stat:
    path: /usr/share/selinux/packages/foss-traffic-capture/dumper_httpd.pp
  register: t
- name: Install traffic capture selinux policy package dumper_httpd
  command: /usr/sbin/semodule -i /usr/share/selinux/packages/foss-traffic-capture/dumper_httpd.pp
  notify: restorecon
  when: t.stat.exists

- name: set required sebooleans..
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  loop:
    - httpd_enable_homedirs
    - httpd_read_user_content
    - httpd_unified

- name: Enable reaper
  systemd:
    name: "{{ item }}"
    enabled: yes
    started: yes
    no_block: no
  loop:
    - reaper
