---
# allow apache reading incoming log. The get_files.cgi and get_file.cgi is hardcoded to only allow
# reading incoming* files and the SELinux rules will not allow apache to read anything else.
# This might be ok since all messages from other hosts that we collect end up in it which is what
# we are interested in.
- acl: 
    path: /var/log/incoming
    entity: apache
    etype: user
    permissions: r
    state: present

- name: Install simple log selinux policy package logger.pp
  shell: /usr/sbin/semodule -i /usr/share/selinux/packages/foss-simple-log/logger.pp

- name: Run restore context to reload selinux
  shell: restorecon -R -v "{{ item }}"
  with_items:
  - /var

- name: Enable rsyslog
  service: name="{{ item }}" enabled=yes state=started
  with_items:
    - rsyslog

