---
- name: Enable and start the httpd server
  service: name=httpd enabled=yes state=started

- name: Install selinux policy package foss_httpd.pp
  shell: /usr/sbin/semodule -i /usr/share/selinux/packages/foss-httpd/foss_httpd.pp

- name: Run restore context to reload selinux
  shell: restorecon -R -v "{{ item }}"
  with_items:
  - /var
